### PR TITLE
Improvements and feature additions

### PR DESCRIPTION
**Pull request by wnagele**
- TLS support
- Build using Maven so that no dependency JAR needs to be included
- Some fixes that cause data loss when shutting down a source

### CODE REVIEW

**Comment by stampy88** [comment]
Hey Wolfgang,

Sorry for being aloof recently. I have been very busy with a start-up and have had zero time to do anything else. I hope to get to this this week sometime.

thanks

dave

---

 From: Wolfgang Nagele reply@reply.github.com
To: dave sinclair stampy88@yahoo.com 
Sent: Thursday, February 23, 2012 8:43 PM
Subject: [flume-amqp-plugin] Improvements and feature additions (#2)
- TLS support
- Build using Maven so that no dependency JAR needs to be included
- Some fixes that cause data loss when shutting down a source

You can merge this Pull Request by running:

 git pull https://github.com/wnagele/flume-plugin-amqp master

Or you can view, comment on it, or merge it online at:

 https://github.com/stampy88/flume-amqp-plugin/pull/2

-- Commit Summary --
- Using Maven for build instead of Ant
- Ignore some stuff
- Instructions for Maven based plugin
- Fixed syntax highlight
- Support TLS connections
- Prevent deadlocks when trying to shutdown the consumer loop
- Only said we would return a null event, but then didn't do it. Would
- Prevent acking all messages that are only put on a non-durable queue.

-- File Changes --

A .gitignore (7)
M README.mkd (48)
D build.xml (61)
D lib/amqp-client-2.1.0.jar (0)
A pom.xml (64)
M src/main/java/amqp/AmqpClient.java (108)
M src/main/java/amqp/AmqpConsumer.java (29)
M src/main/java/amqp/AmqpEventSource.java (31)

-- Patch Links --

 https://github.com/stampy88/flume-amqp-plugin/pull/2.patch
 https://github.com/stampy88/flume-amqp-plugin/pull/2.diff

---

Reply to this email directly or view it on GitHub:
https://github.com/stampy88/flume-amqp-plugin/pull/2

**Comment by wnagele** [comment]
_ping_

**Comment by wnagele** [comment]
Any chance you'll be able to merge in this pull request?

**Comment by wnagele** [comment]
Dead.

**Pull request closed without merging**
